{"asctime": "2023-10-13 10:02:58,843", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 10:03:39,692", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 10:04:16,670", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\finance\\settings.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 10:04:18,445", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 10:04:48,095", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 10:06:34,205", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\views.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 10:06:36,209", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 10:25:28,420", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\views.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 10:25:30,198", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 10:25:56,206", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 10:25:57,867", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 10:28:26,528", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\urls.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 10:28:28,521", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 10:36:10,950", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=780, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 61364)>", "server_time": "13/Oct/2023 10:36:10", "status_code": 200}
{"asctime": "2023-10-13 10:36:21,019", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 10:36:22,773", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 10:36:28,965", "levelname": "ERROR", "name": "django.request", "message": "Internal Server Error: /docs/import420", "filename": "log.py", "funcName": "log_response", "lineno": 241, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\log.py", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 56, in wrapper_view\n    return view_func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\decorators.py\", line 50, in handler\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Finance_Back\\docs\\views.py\", line 1267, in import420\n    pdftotext420(\"imports/420/4-20.pdf\")\n  File \"C:\\Finance_Back\\docs\\shareModuleInc.py\", line 139, in pdftotext420\n    _date = text[3].split(':')[1]\n            ~~~~~~~~~~~~~~~~~~^^^\nIndexError: list index out of range", "status_code": 500, "request": "<WSGIRequest: POST '/docs/import420'>"}
{"asctime": "2023-10-13 10:36:28,973", "levelname": "ERROR", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 500 107422", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2336, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 61382)>", "server_time": "13/Oct/2023 10:36:28", "status_code": 500}
{"asctime": "2023-10-13 10:36:37,806", "levelname": "ERROR", "name": "django.request", "message": "Internal Server Error: /docs/import420", "filename": "log.py", "funcName": "log_response", "lineno": 241, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\log.py", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 56, in wrapper_view\n    return view_func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\decorators.py\", line 50, in handler\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Finance_Back\\docs\\views.py\", line 1267, in import420\n    pdftotext420(\"imports/420/4-20.pdf\")\n  File \"C:\\Finance_Back\\docs\\shareModuleInc.py\", line 139, in pdftotext420\n    _date = text[3].split(':')[1]\n            ~~~~~~~~~~~~~~~~~~^^^\nIndexError: list index out of range", "status_code": 500, "request": "<WSGIRequest: POST '/docs/import420'>"}
{"asctime": "2023-10-13 10:36:37,808", "levelname": "ERROR", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 500 107422", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2336, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 61382)>", "server_time": "13/Oct/2023 10:36:37", "status_code": 500}
{"asctime": "2023-10-13 11:09:39,882", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 11:09:41,324", "levelname": "ERROR", "name": "django.request", "message": "Internal Server Error: /docs/import420", "filename": "log.py", "funcName": "log_response", "lineno": 241, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\log.py", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 56, in wrapper_view\n    return view_func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\decorators.py\", line 50, in handler\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Finance_Back\\docs\\views.py\", line 1267, in import420\n    pdftotext420(\"imports/420/4-20.pdf\")\n  File \"C:\\Finance_Back\\docs\\shareModuleInc.py\", line 139, in pdftotext420\n    for i in range(5, len(text)):\n                ^^^^^^^^^^^^^^^^^^\nIndexError: list index out of range", "status_code": 500, "request": "<WSGIRequest: POST '/docs/import420'>"}
{"asctime": "2023-10-13 11:09:41,330", "levelname": "ERROR", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 500 113249", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2336, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 61382)>", "server_time": "13/Oct/2023 11:09:41", "status_code": 500}
{"asctime": "2023-10-13 11:09:43,069", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 11:12:15,344", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 11:12:17,471", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2340, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 61643)>", "server_time": "13/Oct/2023 11:12:17", "status_code": 200}
{"asctime": "2023-10-13 11:12:19,181", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 11:12:26,787", "levelname": "ERROR", "name": "django.request", "message": "Internal Server Error: /docs/import420", "filename": "log.py", "funcName": "log_response", "lineno": 241, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\log.py", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 56, in wrapper_view\n    return view_func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\decorators.py\", line 50, in handler\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Finance_Back\\docs\\views.py\", line 1267, in import420\n    pdftotext420(\"imports/420/4-20.pdf\")\n  File \"C:\\Finance_Back\\docs\\shareModuleInc.py\", line 149, in pdftotext420\n    print(\"\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043f\u0440\u043e\u0431\u0435\u043b\u043e\u0432 \u043f\u0435\u0440\u0435\u0434 \u043f\u0435\u0440\u0432\u044b\u043c \u043d\u0435\u043f\u0440\u043e\u0431\u0435\u043b\u043d\u044b\u043c \u0441\u0438\u043c\u0432\u043e\u043b\u043e\u043c:\", count)\n                                                                    ^^^^^\nUnboundLocalError: cannot access local variable 'count' where it is not associated with a value", "status_code": 500, "request": "<WSGIRequest: POST '/docs/import420'>"}
{"asctime": "2023-10-13 11:12:26,792", "levelname": "ERROR", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 500 108479", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2332, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 61679)>", "server_time": "13/Oct/2023 11:12:26", "status_code": 500}
{"asctime": "2023-10-13 11:12:51,964", "levelname": "ERROR", "name": "django.request", "message": "Internal Server Error: /docs/import420", "filename": "log.py", "funcName": "log_response", "lineno": 241, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\log.py", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 56, in wrapper_view\n    return view_func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\decorators.py\", line 50, in handler\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Finance_Back\\docs\\views.py\", line 1267, in import420\n    pdftotext420(\"imports/420/4-20.pdf\")\n  File \"C:\\Finance_Back\\docs\\shareModuleInc.py\", line 149, in pdftotext420\n    print(\"\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043f\u0440\u043e\u0431\u0435\u043b\u043e\u0432 \u043f\u0435\u0440\u0435\u0434 \u043f\u0435\u0440\u0432\u044b\u043c \u043d\u0435\u043f\u0440\u043e\u0431\u0435\u043b\u043d\u044b\u043c \u0441\u0438\u043c\u0432\u043e\u043b\u043e\u043c:\", count)\n                                                                    ^^^^^\nUnboundLocalError: cannot access local variable 'count' where it is not associated with a value", "status_code": 500, "request": "<WSGIRequest: POST '/docs/import420'>"}
{"asctime": "2023-10-13 11:12:51,969", "levelname": "ERROR", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 500 108680", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2332, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 61679)>", "server_time": "13/Oct/2023 11:12:51", "status_code": 500}
{"asctime": "2023-10-13 11:13:40,090", "levelname": "ERROR", "name": "django.request", "message": "Internal Server Error: /docs/import420", "filename": "log.py", "funcName": "log_response", "lineno": 241, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\log.py", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 56, in wrapper_view\n    return view_func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\decorators.py\", line 50, in handler\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Finance_Back\\docs\\views.py\", line 1267, in import420\n    pdftotext420(\"imports/420/4-20.pdf\")\n  File \"C:\\Finance_Back\\docs\\shareModuleInc.py\", line 149, in pdftotext420\n    print(\"\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043f\u0440\u043e\u0431\u0435\u043b\u043e\u0432 \u043f\u0435\u0440\u0435\u0434 \u043f\u0435\u0440\u0432\u044b\u043c \u043d\u0435\u043f\u0440\u043e\u0431\u0435\u043b\u043d\u044b\u043c \u0441\u0438\u043c\u0432\u043e\u043b\u043e\u043c:\", count)\n                                                                    ^^^^^\nUnboundLocalError: cannot access local variable 'count' where it is not associated with a value", "status_code": 500, "request": "<WSGIRequest: POST '/docs/import420'>"}
{"asctime": "2023-10-13 11:13:40,092", "levelname": "ERROR", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 500 108479", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2332, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 61679)>", "server_time": "13/Oct/2023 11:13:40", "status_code": 500}
{"asctime": "2023-10-13 11:13:44,102", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 11:13:46,064", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 11:13:49,290", "levelname": "ERROR", "name": "django.request", "message": "Internal Server Error: /docs/import420", "filename": "log.py", "funcName": "log_response", "lineno": 241, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\log.py", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 56, in wrapper_view\n    return view_func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\decorators.py\", line 50, in handler\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Finance_Back\\docs\\views.py\", line 1267, in import420\n    pdftotext420(\"imports/420/4-20.pdf\")\n  File \"C:\\Finance_Back\\docs\\shareModuleInc.py\", line 139, in pdftotext420\n    for i in len(text):\nTypeError: 'int' object is not iterable", "status_code": 500, "request": "<WSGIRequest: POST '/docs/import420'>"}
{"asctime": "2023-10-13 11:13:49,294", "levelname": "ERROR", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 500 107776", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2276, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 61708)>", "server_time": "13/Oct/2023 11:13:49", "status_code": 500}
{"asctime": "2023-10-13 11:13:53,007", "levelname": "ERROR", "name": "django.request", "message": "Internal Server Error: /docs/import420", "filename": "log.py", "funcName": "log_response", "lineno": 241, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\log.py", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 56, in wrapper_view\n    return view_func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\decorators.py\", line 50, in handler\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Finance_Back\\docs\\views.py\", line 1267, in import420\n    pdftotext420(\"imports/420/4-20.pdf\")\n  File \"C:\\Finance_Back\\docs\\shareModuleInc.py\", line 139, in pdftotext420\n    for i in len(text):\nTypeError: 'int' object is not iterable", "status_code": 500, "request": "<WSGIRequest: POST '/docs/import420'>"}
{"asctime": "2023-10-13 11:13:53,011", "levelname": "ERROR", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 500 107776", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2276, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 61708)>", "server_time": "13/Oct/2023 11:13:53", "status_code": 500}
{"asctime": "2023-10-13 11:14:04,616", "levelname": "ERROR", "name": "django.request", "message": "Internal Server Error: /docs/import420", "filename": "log.py", "funcName": "log_response", "lineno": 241, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\log.py", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 56, in wrapper_view\n    return view_func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\decorators.py\", line 50, in handler\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Finance_Back\\docs\\views.py\", line 1267, in import420\n    pdftotext420(\"imports/420/4-20.pdf\")\n  File \"C:\\Finance_Back\\docs\\shareModuleInc.py\", line 139, in pdftotext420\n    for i in len(text):\nTypeError: 'int' object is not iterable", "status_code": 500, "request": "<WSGIRequest: POST '/docs/import420'>"}
{"asctime": "2023-10-13 11:14:04,622", "levelname": "ERROR", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 500 107977", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2276, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 61708)>", "server_time": "13/Oct/2023 11:14:04", "status_code": 500}
{"asctime": "2023-10-13 11:14:13,732", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 11:14:15,677", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 11:14:30,693", "levelname": "ERROR", "name": "django.request", "message": "Internal Server Error: /docs/import420", "filename": "log.py", "funcName": "log_response", "lineno": 241, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\log.py", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 56, in wrapper_view\n    return view_func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\decorators.py\", line 50, in handler\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Finance_Back\\docs\\views.py\", line 1267, in import420\n    pdftotext420(\"imports/420/4-20.pdf\")\n  File \"C:\\Finance_Back\\docs\\shareModuleInc.py\", line 149, in pdftotext420\n    print(\"\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043f\u0440\u043e\u0431\u0435\u043b\u043e\u0432 \u043f\u0435\u0440\u0435\u0434 \u043f\u0435\u0440\u0432\u044b\u043c \u043d\u0435\u043f\u0440\u043e\u0431\u0435\u043b\u043d\u044b\u043c \u0441\u0438\u043c\u0432\u043e\u043b\u043e\u043c:\", count)\n                                                                    ^^^^^\nUnboundLocalError: cannot access local variable 'count' where it is not associated with a value", "status_code": 500, "request": "<WSGIRequest: POST '/docs/import420'>"}
{"asctime": "2023-10-13 11:14:30,701", "levelname": "ERROR", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 500 108680", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2364, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 61729)>", "server_time": "13/Oct/2023 11:14:30", "status_code": 500}
{"asctime": "2023-10-13 11:14:46,989", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 11:14:48,985", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 11:14:59,645", "levelname": "ERROR", "name": "django.request", "message": "Internal Server Error: /docs/import420", "filename": "log.py", "funcName": "log_response", "lineno": 241, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\log.py", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 56, in wrapper_view\n    return view_func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\decorators.py\", line 50, in handler\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Finance_Back\\docs\\views.py\", line 1267, in import420\n    pdftotext420(\"imports/420/4-20.pdf\")\n  File \"C:\\Finance_Back\\docs\\shareModuleInc.py\", line 149, in pdftotext420\n    print(\"\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043f\u0440\u043e\u0431\u0435\u043b\u043e\u0432 \u043f\u0435\u0440\u0435\u0434 \u043f\u0435\u0440\u0432\u044b\u043c \u043d\u0435\u043f\u0440\u043e\u0431\u0435\u043b\u043d\u044b\u043c \u0441\u0438\u043c\u0432\u043e\u043b\u043e\u043c:\", count)\n                                                                    ^^^^^\nUnboundLocalError: cannot access local variable 'count' where it is not associated with a value", "status_code": 500, "request": "<WSGIRequest: POST '/docs/import420'>"}
{"asctime": "2023-10-13 11:14:59,652", "levelname": "ERROR", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 500 108680", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2320, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 61743)>", "server_time": "13/Oct/2023 11:14:59", "status_code": 500}
{"asctime": "2023-10-13 11:22:01,678", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 11:22:03,647", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 11:22:17,037", "levelname": "ERROR", "name": "django.request", "message": "Internal Server Error: /docs/import420", "filename": "log.py", "funcName": "log_response", "lineno": 241, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\log.py", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 56, in wrapper_view\n    return view_func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\decorators.py\", line 50, in handler\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Finance_Back\\docs\\views.py\", line 1267, in import420\n    pdftotext420(\"imports/420/4-20.pdf\")\n  File \"C:\\Finance_Back\\docs\\shareModuleInc.py\", line 149, in pdftotext420\n    print(\"\u041a\u043e\u043b\u0438\u0447\u0435\u0441\u0442\u0432\u043e \u043f\u0440\u043e\u0431\u0435\u043b\u043e\u0432 \u043f\u0435\u0440\u0435\u0434 \u043f\u0435\u0440\u0432\u044b\u043c \u043d\u0435\u043f\u0440\u043e\u0431\u0435\u043b\u043d\u044b\u043c \u0441\u0438\u043c\u0432\u043e\u043b\u043e\u043c:\", count)\n                                                                    ^^^^^\nUnboundLocalError: cannot access local variable 'count' where it is not associated with a value", "status_code": 500, "request": "<WSGIRequest: POST '/docs/import420'>"}
{"asctime": "2023-10-13 11:22:17,045", "levelname": "ERROR", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 500 108680", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2172, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 61792)>", "server_time": "13/Oct/2023 11:22:17", "status_code": 500}
{"asctime": "2023-10-13 11:23:04,198", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 11:23:06,076", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 11:28:19,204", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 11:28:24,099", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2120, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 61812)>", "server_time": "13/Oct/2023 11:28:24", "status_code": 200}
{"asctime": "2023-10-13 11:28:25,991", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 11:28:32,885", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2256, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 61873)>", "server_time": "13/Oct/2023 11:28:32", "status_code": 200}
{"asctime": "2023-10-13 11:40:18,589", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 11:40:20,768", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2256, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 61873)>", "server_time": "13/Oct/2023 11:40:20", "status_code": 200}
{"asctime": "2023-10-13 11:40:22,479", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 11:45:31,533", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 11:45:51,402", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2308, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 62018)>", "server_time": "13/Oct/2023 11:45:51", "status_code": 200}
{"asctime": "2023-10-13 11:45:53,264", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 11:52:12,333", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 11:52:14,167", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 11:52:20,672", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2324, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 62172)>", "server_time": "13/Oct/2023 11:52:20", "status_code": 200}
{"asctime": "2023-10-13 11:53:29,569", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 11:53:31,567", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 11:53:37,122", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2152, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 62203)>", "server_time": "13/Oct/2023 11:53:37", "status_code": 200}
{"asctime": "2023-10-13 11:59:22,626", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 11:59:26,170", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2152, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 62203)>", "server_time": "13/Oct/2023 11:59:26", "status_code": 200}
{"asctime": "2023-10-13 11:59:27,843", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 11:59:32,781", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2344, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 62272)>", "server_time": "13/Oct/2023 11:59:32", "status_code": 200}
{"asctime": "2023-10-13 12:01:00,267", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 12:01:03,787", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2344, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 62272)>", "server_time": "13/Oct/2023 12:01:03", "status_code": 200}
{"asctime": "2023-10-13 12:01:05,458", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 12:01:08,396", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2304, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 62300)>", "server_time": "13/Oct/2023 12:01:08", "status_code": 200}
{"asctime": "2023-10-13 12:01:50,786", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 12:01:51,911", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2304, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 62300)>", "server_time": "13/Oct/2023 12:01:51", "status_code": 200}
{"asctime": "2023-10-13 12:01:53,608", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 12:01:57,146", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2348, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 62321)>", "server_time": "13/Oct/2023 12:01:57", "status_code": 200}
{"asctime": "2023-10-13 12:10:26,759", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 12:10:28,614", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 12:11:27,533", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 12:11:33,663", "levelname": "ERROR", "name": "django.request", "message": "Internal Server Error: /docs/import420", "filename": "log.py", "funcName": "log_response", "lineno": 241, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\log.py", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 56, in wrapper_view\n    return view_func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\decorators.py\", line 50, in handler\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Finance_Back\\docs\\views.py\", line 1267, in import420\n    pdftotext420(\"imports/420/4-20.pdf\")\n  File \"C:\\Finance_Back\\docs\\shareModuleInc.py\", line 161, in pdftotext420\nUnboundLocalError: cannot access local variable 'count' where it is not associated with a value", "status_code": 500, "request": "<WSGIRequest: POST '/docs/import420'>"}
{"asctime": "2023-10-13 12:11:33,671", "levelname": "ERROR", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 500 106930", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=1812, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 62422)>", "server_time": "13/Oct/2023 12:11:33", "status_code": 500}
{"asctime": "2023-10-13 12:11:35,392", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 12:14:56,318", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2312, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 62444)>", "server_time": "13/Oct/2023 12:14:56", "status_code": 200}
{"asctime": "2023-10-13 12:15:26,250", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 12:15:27,973", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 12:15:36,221", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2320, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 62523)>", "server_time": "13/Oct/2023 12:15:36", "status_code": 200}
{"asctime": "2023-10-13 12:15:49,944", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 12:15:51,707", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 12:15:54,307", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2476, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 62541)>", "server_time": "13/Oct/2023 12:15:54", "status_code": 200}
{"asctime": "2023-10-13 12:17:29,547", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 12:17:31,244", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 12:17:35,311", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2312, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 62592)>", "server_time": "13/Oct/2023 12:17:35", "status_code": 200}
{"asctime": "2023-10-13 12:19:51,243", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2312, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 62592)>", "server_time": "13/Oct/2023 12:19:51", "status_code": 200}
{"asctime": "2023-10-13 12:20:00,691", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 12:20:02,662", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 12:21:14,957", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=784, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 62623)>", "server_time": "13/Oct/2023 12:21:14", "status_code": 200}
{"asctime": "2023-10-13 12:21:55,800", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 12:21:57,053", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=784, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 62623)>", "server_time": "13/Oct/2023 12:21:57", "status_code": 200}
{"asctime": "2023-10-13 12:21:59,023", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 12:22:05,439", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2308, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 62676)>", "server_time": "13/Oct/2023 12:22:05", "status_code": 200}
{"asctime": "2023-10-13 12:39:14,527", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 15:22:48,275", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2308, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 62676)>", "server_time": "13/Oct/2023 15:22:48", "status_code": 200}
{"asctime": "2023-10-13 15:22:50,106", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 15:22:53,422", "levelname": "ERROR", "name": "django.request", "message": "Internal Server Error: /docs/import420", "filename": "log.py", "funcName": "log_response", "lineno": 241, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\log.py", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 56, in wrapper_view\n    return view_func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\decorators.py\", line 50, in handler\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Finance_Back\\docs\\views.py\", line 1267, in import420\n    pdftotext420(\"imports/420/4-20.pdf\")\n  File \"C:\\Finance_Back\\docs\\shareModuleInc.py\", line 209, in pdftotext420\n    txt = text[item].split()[len(text[item].split())-10]\n          ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nIndexError: list index out of range", "status_code": 500, "request": "<WSGIRequest: POST '/docs/import420'>"}
{"asctime": "2023-10-13 15:22:53,426", "levelname": "ERROR", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 500 111348", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2376, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 63566)>", "server_time": "13/Oct/2023 15:22:53", "status_code": 500}
{"asctime": "2023-10-13 15:22:56,404", "levelname": "ERROR", "name": "django.request", "message": "Internal Server Error: /docs/import420", "filename": "log.py", "funcName": "log_response", "lineno": 241, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\log.py", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 56, in wrapper_view\n    return view_func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\decorators.py\", line 50, in handler\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Finance_Back\\docs\\views.py\", line 1267, in import420\n    pdftotext420(\"imports/420/4-20.pdf\")\n  File \"C:\\Finance_Back\\docs\\shareModuleInc.py\", line 209, in pdftotext420\n    txt = text[item].split()[len(text[item].split())-10]\n          ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nIndexError: list index out of range", "status_code": 500, "request": "<WSGIRequest: POST '/docs/import420'>"}
{"asctime": "2023-10-13 15:22:56,407", "levelname": "ERROR", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 500 111348", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2376, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 63566)>", "server_time": "13/Oct/2023 15:22:56", "status_code": 500}
{"asctime": "2023-10-13 15:24:41,857", "levelname": "ERROR", "name": "django.request", "message": "Internal Server Error: /docs/import420", "filename": "log.py", "funcName": "log_response", "lineno": 241, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\log.py", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 56, in wrapper_view\n    return view_func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\decorators.py\", line 50, in handler\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Finance_Back\\docs\\views.py\", line 1267, in import420\n    pdftotext420(\"imports/420/4-20.pdf\")\n  File \"C:\\Finance_Back\\docs\\shareModuleInc.py\", line 209, in pdftotext420\n    txt = text[item].split()[len(text[item].split())-10]\n          ~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^\nIndexError: list index out of range", "status_code": 500, "request": "<WSGIRequest: POST '/docs/import420'>"}
{"asctime": "2023-10-13 15:24:41,864", "levelname": "ERROR", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 500 111348", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2376, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 63566)>", "server_time": "13/Oct/2023 15:24:41", "status_code": 500}
{"asctime": "2023-10-13 15:24:48,383", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 15:24:50,315", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 15:34:03,001", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 15:34:07,059", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2184, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 63594)>", "server_time": "13/Oct/2023 15:34:07", "status_code": 200}
{"asctime": "2023-10-13 15:34:08,711", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 15:34:29,199", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2332, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 63699)>", "server_time": "13/Oct/2023 15:34:29", "status_code": 200}
{"asctime": "2023-10-13 15:36:44,060", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 15:36:45,983", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 15:37:12,697", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 15:37:15,338", "levelname": "ERROR", "name": "django.request", "message": "Internal Server Error: /docs/import420", "filename": "log.py", "funcName": "log_response", "lineno": 241, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\log.py", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Finance_Back\\docs\\shareModuleInc.py\", line 211, in pdftotext420\n    sum[i] = float(txt.replace(',', ''))\n    ~~~^^^\nTypeError: 'builtin_function_or_method' object does not support item assignment\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 56, in wrapper_view\n    return view_func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\decorators.py\", line 50, in handler\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Finance_Back\\docs\\views.py\", line 1267, in import420\n    pdftotext420(\"imports/420/4-20.pdf\")\n  File \"C:\\Finance_Back\\docs\\shareModuleInc.py\", line 213, in pdftotext420\n    sum[i] = ''.join(\n    ~~~^^^\nTypeError: 'builtin_function_or_method' object does not support item assignment", "status_code": 500, "request": "<WSGIRequest: POST '/docs/import420'>"}
{"asctime": "2023-10-13 15:37:15,344", "levelname": "ERROR", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 500 127200", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=1800, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 63725)>", "server_time": "13/Oct/2023 15:37:15", "status_code": 500}
{"asctime": "2023-10-13 15:37:17,065", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 15:38:06,044", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 15:38:07,781", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 15:45:41,498", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 15:45:43,712", "levelname": "ERROR", "name": "django.request", "message": "Internal Server Error: /docs/import420", "filename": "log.py", "funcName": "log_response", "lineno": 241, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\log.py", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Finance_Back\\docs\\shareModuleInc.py\", line 211, in pdftotext420\n    # \u0418\u0437\u0432\u043b\u0435\u0447\u0435\u043d\u0438\u0435 \u0442\u0430\u0431\u043b\u0438\u0446\u044b \u0438\u0437 PDF\n                  ^^^\nTypeError: 'builtin_function_or_method' object does not support item assignment\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 56, in wrapper_view\n    return view_func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\decorators.py\", line 50, in handler\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Finance_Back\\docs\\views.py\", line 1267, in import420\n    pdftotext420(\"imports/420/4-20.pdf\")\n  File \"C:\\Finance_Back\\docs\\shareModuleInc.py\", line 213, in pdftotext420\nTypeError: 'builtin_function_or_method' object does not support item assignment", "status_code": 500, "request": "<WSGIRequest: POST '/docs/import420'>"}
{"asctime": "2023-10-13 15:45:43,720", "levelname": "ERROR", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 500 124392", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2340, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 63781)>", "server_time": "13/Oct/2023 15:45:43", "status_code": 500}
{"asctime": "2023-10-13 15:45:45,575", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 15:46:49,689", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 15:46:55,501", "levelname": "ERROR", "name": "django.request", "message": "Internal Server Error: /docs/import420", "filename": "log.py", "funcName": "log_response", "lineno": 241, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\log.py", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Finance_Back\\docs\\shareModuleInc.py\", line 199, in pdftotext420\n    sums[i] = float(txt.replace(',', ''))\n    ~~~~^^^\nIndexError: list assignment index out of range\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 56, in wrapper_view\n    return view_func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\decorators.py\", line 50, in handler\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Finance_Back\\docs\\views.py\", line 1267, in import420\n    pdftotext420(\"imports/420/4-20.pdf\")\n  File \"C:\\Finance_Back\\docs\\shareModuleInc.py\", line 201, in pdftotext420\n    sums[i] = ''.join(\n    ~~~~^^^\nIndexError: list assignment index out of range", "status_code": 500, "request": "<WSGIRequest: POST '/docs/import420'>"}
{"asctime": "2023-10-13 15:46:55,507", "levelname": "ERROR", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 500 123556", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=824, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 63883)>", "server_time": "13/Oct/2023 15:46:55", "status_code": 500}
{"asctime": "2023-10-13 15:46:57,126", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 15:47:33,699", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 15:47:36,800", "levelname": "ERROR", "name": "django.request", "message": "Internal Server Error: /docs/import420", "filename": "log.py", "funcName": "log_response", "lineno": 241, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\log.py", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Finance_Back\\docs\\shareModuleInc.py\", line 199, in pdftotext420\n    sums[i - 1] = float(txt.replace(',', ''))\n    ^^^^^^^\nIndexError: list assignment index out of range\n\nDuring handling of the above exception, another exception occurred:\n\nTraceback (most recent call last):\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 56, in wrapper_view\n    return view_func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\decorators.py\", line 50, in handler\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Finance_Back\\docs\\views.py\", line 1267, in import420\n    pdftotext420(\"imports/420/4-20.pdf\")\n  File \"C:\\Finance_Back\\docs\\shareModuleInc.py\", line 201, in pdftotext420\n    sums[i - 1] = ''.join(\n    ^^^^^^^\nIndexError: list assignment index out of range", "status_code": 500, "request": "<WSGIRequest: POST '/docs/import420'>"}
{"asctime": "2023-10-13 15:47:36,807", "levelname": "ERROR", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 500 123620", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2312, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 63930)>", "server_time": "13/Oct/2023 15:47:36", "status_code": 500}
{"asctime": "2023-10-13 15:47:38,382", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 15:52:20,947", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 15:52:36,459", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2376, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 63951)>", "server_time": "13/Oct/2023 15:52:36", "status_code": 200}
{"asctime": "2023-10-13 15:52:38,222", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 15:52:40,974", "levelname": "ERROR", "name": "django.request", "message": "Internal Server Error: /docs/import420", "filename": "log.py", "funcName": "log_response", "lineno": 241, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\log.py", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 56, in wrapper_view\n    return view_func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\decorators.py\", line 50, in handler\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Finance_Back\\docs\\views.py\", line 1267, in import420\n    pdftotext420(\"imports/420/4-20.pdf\")\n  File \"C:\\Finance_Back\\docs\\shareModuleInc.py\", line 204, in pdftotext420\n    print(abp + '/' + bp + '/' +\n          ^^^^^^^^^^^^^^^^^^^^^^\nTypeError: can only concatenate str (not \"list\") to str", "status_code": 500, "request": "<WSGIRequest: POST '/docs/import420'>"}
{"asctime": "2023-10-13 15:52:40,978", "levelname": "ERROR", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 500 109909", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2296, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 64039)>", "server_time": "13/Oct/2023 15:52:40", "status_code": 500}
{"asctime": "2023-10-13 15:53:55,723", "levelname": "ERROR", "name": "django.request", "message": "Internal Server Error: /docs/import420", "filename": "log.py", "funcName": "log_response", "lineno": 241, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\log.py", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 56, in wrapper_view\n    return view_func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\decorators.py\", line 50, in handler\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Finance_Back\\docs\\views.py\", line 1267, in import420\n    pdftotext420(\"imports/420/4-20.pdf\")\n  File \"C:\\Finance_Back\\docs\\shareModuleInc.py\", line 204, in pdftotext420\n    print(abp + '/' + bp + '/' +\n          ^^^^^^^^^^^^^^^^^^^^^^\nTypeError: can only concatenate str (not \"list\") to str", "status_code": 500, "request": "<WSGIRequest: POST '/docs/import420'>"}
{"asctime": "2023-10-13 15:53:55,729", "levelname": "ERROR", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 500 109909", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2296, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 64039)>", "server_time": "13/Oct/2023 15:53:55", "status_code": 500}
{"asctime": "2023-10-13 15:54:36,354", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 15:54:38,169", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 15:54:42,181", "levelname": "ERROR", "name": "django.request", "message": "Internal Server Error: /docs/import420", "filename": "log.py", "funcName": "log_response", "lineno": 241, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\log.py", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 56, in wrapper_view\n    return view_func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\decorators.py\", line 50, in handler\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Finance_Back\\docs\\views.py\", line 1267, in import420\n    pdftotext420(\"imports/420/4-20.pdf\")\n  File \"C:\\Finance_Back\\docs\\shareModuleInc.py\", line 204, in pdftotext420\n    print(abp + '/' + bp + '/' +\n          ^^^^^^^^^^^^^^^^^^^^^^\nTypeError: can only concatenate str (not \"list\") to str", "status_code": 500, "request": "<WSGIRequest: POST '/docs/import420'>"}
{"asctime": "2023-10-13 15:54:42,185", "levelname": "ERROR", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 500 110060", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2300, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 64076)>", "server_time": "13/Oct/2023 15:54:42", "status_code": 500}
{"asctime": "2023-10-13 15:56:14,943", "levelname": "ERROR", "name": "django.request", "message": "Internal Server Error: /docs/import420", "filename": "log.py", "funcName": "log_response", "lineno": 241, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\log.py", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 56, in wrapper_view\n    return view_func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\decorators.py\", line 50, in handler\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Finance_Back\\docs\\views.py\", line 1267, in import420\n    pdftotext420(\"imports/420/4-20.pdf\")\n  File \"C:\\Finance_Back\\docs\\shareModuleInc.py\", line 204, in pdftotext420\n    print(abp + '/' + bp + '/' +\n          ^^^^^^^^^^^^^^^^^^^^^^\nTypeError: can only concatenate str (not \"list\") to str", "status_code": 500, "request": "<WSGIRequest: POST '/docs/import420'>"}
{"asctime": "2023-10-13 15:56:14,950", "levelname": "ERROR", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 500 110261", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2300, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 64076)>", "server_time": "13/Oct/2023 15:56:14", "status_code": 500}
{"asctime": "2023-10-13 15:56:29,319", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 15:56:31,235", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 15:56:39,398", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2372, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 64118)>", "server_time": "13/Oct/2023 15:56:39", "status_code": 200}
{"asctime": "2023-10-13 15:56:56,670", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 15:56:58,415", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 15:57:00,709", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2084, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 64136)>", "server_time": "13/Oct/2023 15:57:00", "status_code": 200}
{"asctime": "2023-10-13 15:59:50,184", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 15:59:52,503", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2084, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 64136)>", "server_time": "13/Oct/2023 15:59:52", "status_code": 200}
{"asctime": "2023-10-13 15:59:54,324", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 16:02:18,872", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 16:02:21,074", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2336, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 64178)>", "server_time": "13/Oct/2023 16:02:21", "status_code": 200}
{"asctime": "2023-10-13 16:02:22,778", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 16:02:42,263", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 16:02:44,067", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 16:02:48,166", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2380, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 64251)>", "server_time": "13/Oct/2023 16:02:48", "status_code": 200}
{"asctime": "2023-10-13 16:03:22,424", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 16:03:24,140", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 16:03:26,496", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2344, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 64268)>", "server_time": "13/Oct/2023 16:03:26", "status_code": 200}
{"asctime": "2023-10-13 16:05:46,413", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 16:05:48,395", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 16:05:51,611", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2252, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 64291)>", "server_time": "13/Oct/2023 16:05:51", "status_code": 200}
{"asctime": "2023-10-13 16:05:59,642", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 16:06:01,641", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 16:06:08,055", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2648, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 64306)>", "server_time": "13/Oct/2023 16:06:08", "status_code": 200}
{"asctime": "2023-10-13 16:06:13,867", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\shareModuleInc.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 16:06:15,845", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 16:06:20,454", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2376, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 64318)>", "server_time": "13/Oct/2023 16:06:20", "status_code": 200}
{"asctime": "2023-10-13 16:14:41,464", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2376, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 64318)>", "server_time": "13/Oct/2023 16:14:41", "status_code": 200}
{"asctime": "2023-10-13 17:03:15,996", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\views.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 17:03:17,814", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 17:05:43,221", "levelname": "INFO", "name": "django.server", "message": "\"OPTIONS /dirs/getinfo HTTP/1.1\" 200 0", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2404, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 65262)>", "server_time": "13/Oct/2023 17:05:43", "status_code": 200}
{"asctime": "2023-10-13 17:05:43,518", "levelname": "INFO", "name": "django.server", "message": "\"GET /dirs/getinfo HTTP/1.1\" 200 1207", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2404, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 65262)>", "server_time": "13/Oct/2023 17:05:43", "status_code": 200}
{"asctime": "2023-10-13 17:05:48,706", "levelname": "INFO", "name": "django.server", "message": "\"OPTIONS /docs/import420 HTTP/1.1\" 200 0", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2404, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 65262)>", "server_time": "13/Oct/2023 17:05:48", "status_code": 200}
{"asctime": "2023-10-13 17:06:58,495", "levelname": "INFO", "name": "django.utils.autoreload", "message": "C:\\Finance_Back\\docs\\views.py changed, reloading.", "filename": "autoreload.py", "funcName": "trigger_reload", "lineno": 266, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 17:07:02,467", "levelname": "INFO", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 200 58", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2404, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 65262)>", "server_time": "13/Oct/2023 17:07:02", "status_code": 200}
{"asctime": "2023-10-13 17:07:04,317", "levelname": "INFO", "name": "django.utils.autoreload", "message": "Watching for file changes with StatReloader", "filename": "autoreload.py", "funcName": "run_with_reloader", "lineno": 668, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\autoreload.py"}
{"asctime": "2023-10-13 17:07:34,140", "levelname": "ERROR", "name": "django.request", "message": "Internal Server Error: /docs/import420", "filename": "log.py", "funcName": "log_response", "lineno": 241, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\utils\\log.py", "exc_info": "Traceback (most recent call last):\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\exception.py\", line 55, in inner\n    response = get_response(request)\n               ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\handlers\\base.py\", line 197, in _get_response\n    response = wrapped_callback(request, *callback_args, **callback_kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\decorators\\csrf.py\", line 56, in wrapper_view\n    return view_func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\django\\views\\generic\\base.py\", line 104, in view\n    return self.dispatch(request, *args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 509, in dispatch\n    response = self.handle_exception(exc)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 469, in handle_exception\n    self.raise_uncaught_exception(exc)\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 480, in raise_uncaught_exception\n    raise exc\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\views.py\", line 506, in dispatch\n    response = handler(request, *args, **kwargs)\n               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\rest_framework\\decorators.py\", line 50, in handler\n    return func(*args, **kwargs)\n           ^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Finance_Back\\docs\\views.py\", line 1274, in import420\n    pdftotext420(pdf_data)\n  File \"C:\\Finance_Back\\docs\\shareModuleInc.py\", line 125, in pdftotext420\n    pdffileobj = open(filename, 'rb')\n                 ^^^^^^^^^^^^^^^^^^^^\nUnicodeDecodeError: 'utf-8' codec can't decode byte 0xa1 in position 11: invalid start byte", "status_code": 500, "request": "<WSGIRequest: POST '/docs/import420'>"}
{"asctime": "2023-10-13 17:07:34,170", "levelname": "ERROR", "name": "django.server", "message": "\"POST /docs/import420 HTTP/1.1\" 500 141299", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=1448, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 65323)>", "server_time": "13/Oct/2023 17:07:34", "status_code": 500}
{"asctime": "2023-10-14 20:02:56,575", "levelname": "INFO", "name": "django.server", "message": "\"OPTIONS /api/auth/token/logout HTTP/1.1\" 200 0", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2808, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 52235)>", "server_time": "14/Oct/2023 20:02:56", "status_code": 200}
{"asctime": "2023-10-14 20:02:56,855", "levelname": "INFO", "name": "django.server", "message": "\"POST /api/auth/token/logout HTTP/1.1\" 204 0", "filename": "basehttp.py", "funcName": "log_message", "lineno": 212, "pathname": "C:\\Program Files\\Python311\\Lib\\site-packages\\django\\core\\servers\\basehttp.py", "request": "<socket.socket fd=2808, family=2, type=1, proto=0, laddr=('192.168.10.251', 8000), raddr=('192.168.10.251', 52235)>", "server_time": "14/Oct/2023 20:02:56", "status_code": 204}
